# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(917, 652)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 30, 351, 291))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 71, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.toolButton = QtWidgets.QToolButton(self.groupBox)
        self.toolButton.setGeometry(QtCore.QRect(250, 30, 81, 31))
        self.toolButton.setObjectName("toolButton")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(10, 240, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setGeometry(QtCore.QRect(110, 240, 231, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser.setGeometry(QtCore.QRect(100, 30, 141, 31))
        self.textBrowser.setOpenLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser_2.setGeometry(QtCore.QRect(100, 80, 141, 31))
        self.textBrowser_2.setOpenLinks(True)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.toolButton_2 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_2.setGeometry(QtCore.QRect(250, 80, 81, 31))
        self.toolButton_2.setObjectName("toolButton_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser_3.setGeometry(QtCore.QRect(100, 130, 141, 31))
        self.textBrowser_3.setOpenLinks(True)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.toolButton_3 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_3.setGeometry(QtCore.QRect(250, 130, 81, 31))
        self.toolButton_3.setObjectName("toolButton_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 180, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser_4.setGeometry(QtCore.QRect(100, 180, 141, 31))
        self.textBrowser_4.setOpenLinks(True)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.toolButton_4 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_4.setGeometry(QtCore.QRect(250, 180, 81, 31))
        self.toolButton_4.setObjectName("toolButton_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(450, 30, 431, 291))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.groupBox_2)
        self.textBrowser_5.setGeometry(QtCore.QRect(130, 30, 141, 31))
        self.textBrowser_5.setOpenLinks(True)
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.toolButton_5 = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_5.setGeometry(QtCore.QRect(290, 30, 81, 31))
        self.toolButton_5.setObjectName("toolButton_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 80, 81, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.progressBar_2 = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressBar_2.setGeometry(QtCore.QRect(110, 80, 161, 31))
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName("progressBar_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 180, 131, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(250, 180, 131, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 230, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.progressBar_3 = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressBar_3.setGeometry(QtCore.QRect(130, 230, 151, 31))
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setTextVisible(True)
        self.progressBar_3.setInvertedAppearance(False)
        self.progressBar_3.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_3.setObjectName("progressBar_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setGeometry(QtCore.QRect(290, 230, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_7.setGeometry(QtCore.QRect(290, 80, 131, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 130, 81, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.progressBar_4 = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressBar_4.setGeometry(QtCore.QRect(110, 130, 281, 31))
        self.progressBar_4.setProperty("value", 0)
        self.progressBar_4.setObjectName("progressBar_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 340, 861, 251))
        self.groupBox_3.setObjectName("groupBox_3")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit.setGeometry(QtCore.QRect(80, 20, 291, 71))
        self.textEdit.setObjectName("textEdit")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(10, 40, 71, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.toolButton_6 = QtWidgets.QToolButton(self.groupBox_3)
        self.toolButton_6.setGeometry(QtCore.QRect(380, 40, 81, 31))
        self.toolButton_6.setObjectName("toolButton_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(10, 130, 101, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_2.setGeometry(QtCore.QRect(80, 120, 291, 111))
        self.textEdit_2.setObjectName("textEdit_2")
        self.toolButton_7 = QtWidgets.QToolButton(self.groupBox_3)
        self.toolButton_7.setGeometry(QtCore.QRect(380, 140, 81, 31))
        self.toolButton_7.setObjectName("toolButton_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(10, 160, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.line = QtWidgets.QFrame(self.groupBox_3)
        self.line.setGeometry(QtCore.QRect(470, 10, 20, 241))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(630, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(490, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textBrowser_6.setGeometry(QtCore.QRect(610, 50, 141, 31))
        self.textBrowser_6.setOpenLinks(True)
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.toolButton_8 = QtWidgets.QToolButton(self.groupBox_3)
        self.toolButton_8.setGeometry(QtCore.QRect(770, 50, 81, 31))
        self.toolButton_8.setObjectName("toolButton_8")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton.setGeometry(QtCore.QRect(590, 100, 61, 16))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_2.setGeometry(QtCore.QRect(670, 100, 61, 16))
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(490, 90, 81, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.toolButton_9 = QtWidgets.QToolButton(self.groupBox_3)
        self.toolButton_9.setGeometry(QtCore.QRect(770, 90, 81, 31))
        self.toolButton_9.setObjectName("toolButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_10.setGeometry(QtCore.QRect(500, 190, 141, 31))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_11.setGeometry(QtCore.QRect(700, 190, 141, 31))
        self.pushButton_11.setObjectName("pushButton_11")
        self.progressBar_5 = QtWidgets.QProgressBar(self.groupBox_3)
        self.progressBar_5.setGeometry(QtCore.QRect(490, 130, 251, 31))
        self.progressBar_5.setProperty("value", 0)
        self.progressBar_5.setObjectName("progressBar_5")
        self.toolButton_10 = QtWidgets.QToolButton(self.groupBox_3)
        self.toolButton_10.setGeometry(QtCore.QRect(740, 130, 111, 31))
        self.toolButton_10.setObjectName("toolButton_10")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(830, 0, 75, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 917, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menuBar.setFont(font)
        self.menuBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menuBar.setObjectName("menuBar")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuAbout = QtWidgets.QMenu(self.menuBar)
        self.menuAbout.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.menuAbout.setAutoFillBackground(True)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menuBar)
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "直播弹幕情感分析系统"))
        self.groupBox.setTitle(_translate("MainWindow", "上传自定义词典"))
        self.label.setText(_translate("MainWindow", "分词词典"))
        self.toolButton.setText(_translate("MainWindow", "选择文件"))
        self.pushButton.setText(_translate("MainWindow", "上传"))
        self.label_2.setText(_translate("MainWindow", "停用词词典"))
        self.toolButton_2.setText(_translate("MainWindow", "选择文件"))
        self.label_3.setText(_translate("MainWindow", "正面词词典"))
        self.toolButton_3.setText(_translate("MainWindow", "选择文件"))
        self.label_4.setText(_translate("MainWindow", "负面词词典"))
        self.toolButton_4.setText(_translate("MainWindow", "选择文件"))
        self.groupBox_2.setTitle(_translate("MainWindow", "数据清洗和预处理"))
        self.label_5.setText(_translate("MainWindow", "上传弹幕数据"))
        self.toolButton_5.setText(_translate("MainWindow", "选择文件"))
        self.pushButton_2.setText(_translate("MainWindow", "开始清洗"))
        self.pushButton_3.setText(_translate("MainWindow", "生成词频数据"))
        self.pushButton_4.setText(_translate("MainWindow", "生成词云图"))
        self.pushButton_5.setText(_translate("MainWindow", "情感词扩充"))
        self.pushButton_6.setText(_translate("MainWindow", "下载新情感词典"))
        self.pushButton_7.setText(_translate("MainWindow", "下载清洗后数据"))
        self.pushButton_8.setText(_translate("MainWindow", "词频分析"))
        self.groupBox_3.setTitle(_translate("MainWindow", "情感分析"))
        self.label_6.setText(_translate("MainWindow", "单条弹幕"))
        self.toolButton_6.setText(_translate("MainWindow", "分析结果"))
        self.label_7.setText(_translate("MainWindow", "多条弹幕"))
        self.toolButton_7.setText(_translate("MainWindow", "分析结果"))
        self.label_8.setText(_translate("MainWindow", "(列表格式)"))
        self.label_9.setText(_translate("MainWindow", "弹幕情感监测"))
        self.label_10.setText(_translate("MainWindow", "上传已清洗数据"))
        self.toolButton_8.setText(_translate("MainWindow", "选择文件"))
        self.radioButton.setText(_translate("MainWindow", "30s"))
        self.radioButton_2.setText(_translate("MainWindow", "60s"))
        self.label_11.setText(_translate("MainWindow", "时间间隔"))
        self.toolButton_9.setText(_translate("MainWindow", "开始分析"))
        self.pushButton_10.setText(_translate("MainWindow", "生成情感曲线图"))
        self.pushButton_11.setText(_translate("MainWindow", "生成情感监测报告"))
        self.toolButton_10.setText(_translate("MainWindow", "下载分析数据"))
        self.pushButton_9.setText(_translate("MainWindow", "重置"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
